auth:
  enabled: false
  providers:
      # # example provider
      # - label: 'google oidc'                        # for internal use; in future may expose as button text
      #   type: oidc                                  # for futureproofing; only oidc is supported today
      #   issuer: https://accounts.google.com
      #   client_id: xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #   client_secret: xxxxxxxxxxxxxxxxxxxxxxx
      #   scope: openid profile email
      #   callback_base_uri: http://localhost:8088

# for more info see docs: https://github.com/temporalio/web#configuring-authentication-optional
